"""Initial tables

Revision ID: 1411869c3a16
Revises: 
Create Date: 2026-01-09 23:51:59.245095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1411869c3a16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('agent_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('context_key', sa.String(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=False),
    sa.Column('embedding_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_contexts_context_key'), 'agent_contexts', ['context_key'], unique=False)
    op.create_index(op.f('ix_agent_contexts_id'), 'agent_contexts', ['id'], unique=False)
    op.create_table('context_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('response_context_id', sa.Integer(), nullable=True),
    sa.Column('response_summary', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['response_context_id'], ['agent_contexts.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_context_requests_id'), 'context_requests', ['id'], unique=False)
    op.create_index(op.f('ix_context_requests_request_id'), 'context_requests', ['request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_context_requests_request_id'), table_name='context_requests')
    op.drop_index(op.f('ix_context_requests_id'), table_name='context_requests')
    op.drop_table('context_requests')
    op.drop_index(op.f('ix_agent_contexts_id'), table_name='agent_contexts')
    op.drop_index(op.f('ix_agent_contexts_context_key'), table_name='agent_contexts')
    op.drop_table('agent_contexts')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
